export const languageOptions = [
  createLanguageOption(63, "JavaScript (Node.js 12.14.0)", "javascript"),
  createLanguageOption(45, "Assembly (NASM 2.14.02)", "assembly"),
  createLanguageOption(46, "Bash (5.0.0)", "bash"),
  createLanguageOption(47, "Basic (FBC 1.07.1)", "basic"),
  createLanguageOption(75, "C (Clang 7.0.1)", "c"),
  createLanguageOption(76, "C++ (Clang 7.0.1)", "cpp"),
  createLanguageOption(48, "C (GCC 7.4.0)", "c"),
  createLanguageOption(52, "C++ (GCC 7.4.0)", "cpp"),
  createLanguageOption(49, "C (GCC 8.3.0)", "c"),
  createLanguageOption(53, "C++ (GCC 8.3.0)", "cpp"),
  createLanguageOption(50, "C (GCC 9.2.0)", "c"),
  createLanguageOption(54, "C++ (GCC 9.2.0)", "cpp"),
  createLanguageOption(86, "Clojure (1.10.1)", "clojure"),
  createLanguageOption(51, "C# (Mono 6.6.0.161)", "csharp"),
  createLanguageOption(77, "COBOL (GnuCOBOL 2.2)", "cobol"),
  createLanguageOption(55, "Common Lisp (SBCL 2.0.0)", "lisp"),
  createLanguageOption(56, "D (DMD 2.089.1)", "d"),
  createLanguageOption(57, "Elixir (1.9.4)", "elixir"),
  createLanguageOption(58, "Erlang (OTP 22.2)", "erlang"),
  createLanguageOption(44, "Executable", "exe"),
  createLanguageOption(87, "F# (.NET Core SDK 3.1.202)", "fsharp"),
  createLanguageOption(59, "Fortran (GFortran 9.2.0)", "fortran"),
  createLanguageOption(60, "Go (1.13.5)", "go"),
  createLanguageOption(88, "Groovy (3.0.3)", "groovy"),
  createLanguageOption(61, "Haskell (GHC 8.8.1)", "haskell"),
  createLanguageOption(62, "Java (OpenJDK 13.0.1)", "java"),
  createLanguageOption(78, "Kotlin (1.3.70)", "kotlin"),
  createLanguageOption(64, "Lua (5.3.5)", "lua"),
  createLanguageOption(79, "Objective-C (Clang 7.0.1)", "objectivec"),
  createLanguageOption(65, "OCaml (4.09.0)", "ocaml"),
  createLanguageOption(66, "Octave (5.1.0)", "octave"),
  createLanguageOption(67, "Pascal (FPC 3.0.4)", "pascal"),
  createLanguageOption(85, "Perl (5.28.1)", "perl"),
  createLanguageOption(68, "PHP (7.4.1)", "php"),
  createLanguageOption(43, "Plain Text", "text"),
  createLanguageOption(69, "Prolog (GNU Prolog 1.4.5)", "prolog"),
  createLanguageOption(70, "Python (2.7.17)", "python"),
  createLanguageOption(71, "Python (3.8.1)", "python"),
  createLanguageOption(80, "R (4.0.0)", "r"),
  createLanguageOption(72, "Ruby (2.7.0)", "ruby"),
  createLanguageOption(73, "Rust (1.40.0)", "rust"),
  createLanguageOption(81, "Scala (2.13.2)", "scala"),
  createLanguageOption(82, "SQL (SQLite 3.27.2)", "sql"),
  createLanguageOption(83, "Swift (5.2.3)", "swift"),
  createLanguageOption(74, "TypeScript (3.7.4)", "typescript"),
  createLanguageOption(84, "Visual Basic.Net (vbnc 0.0.0.5943)", "vbnet"),
];

function createLanguageOption(id, name, value) {
  return {
    id,
    name,
    label: name,
    value,
  };
}
